package com.dcube.jarvis.models

import org.apache.spark.sql.types._

object JarvisStructTypes {

  val SalesCustomer: StructType = StructType (List(
    StructField("Id", StringType, nullable = false)
    ,StructField("IdActivity", StringType, nullable = false)
    ,StructField("Siret", StringType, nullable = false)
    ,StructField("VatNumber", StringType, nullable = false)
    ,StructField("Company", StringType, nullable = false)
    ,StructField("Form", StringType, nullable = true)
    ,StructField("Attention", StringType, nullable = false)
    ,StructField("Address1", StringType, nullable = false)
    ,StructField("Address2", StringType, nullable = true)
    ,StructField("Address3", StringType, nullable = true)
    ,StructField("ZipCode", StringType, nullable = false)
    ,StructField("Town", StringType, nullable = false)
    ,StructField("CreateDate", TimestampType, nullable = false)
    ,StructField("CustomerCode", StringType, nullable = false)
    ,StructField("PhoneNumber", StringType, nullable = true)
    ,StructField("Fax", StringType, nullable = true)
    ,StructField("Groupe", StringType, nullable = true)
    ,StructField("Status", IntegerType, nullable = true)
    ,StructField("PaymentDelay", IntegerType, nullable = false)
    ,StructField("SendingType", StringType, nullable = true)
    ,StructField("EmailRecipient", StringType, nullable = true)
  ))

  val SalesIntervention: StructType = StructType (List(
    StructField("Id", StringType, nullable = false)
    ,StructField("IdUser", StringType, nullable = false)
    ,StructField("IdPhasis", StringType, nullable = false)
    ,StructField("IdRole", StringType, nullable = false)
    ,StructField("DailyCost", DoubleType, nullable = false)
    ,StructField("DailyPrice", DoubleType, nullable = false)
    ,StructField("StartDate", TimestampType, nullable = false)
    ,StructField("EndDate", TimestampType, nullable = true)
    ,StructField("ManagerName", StringType, nullable = false)
    ,StructField("Quantity", DoubleType, nullable = true)
    ,StructField("Consumed", DoubleType, nullable = false)
    ,StructField("InvoiceLabel", StringType, nullable = false)
    ,StructField("TimesheetLabel", StringType, nullable = false)
    ,StructField("InvoiceAffected", IntegerType, nullable = false)
    ,StructField("DailyCharges", DoubleType, nullable = false)
    ,StructField("IdAddress", StringType, nullable = true)
  ))

  val SalesLead: StructType = StructType (List(
    StructField("Id", StringType, nullable = false)
    ,StructField("IdUser", StringType, nullable = false)
    ,StructField("IdCustomer", StringType, nullable = false)
    ,StructField("IdContact", StringType, nullable = true)
    ,StructField("CreateDate", StringType, nullable = false)
    ,StructField("DueDate", StringType, nullable = true)
    ,StructField("LastStatusDate", StringType, nullable = false)
    ,StructField("ShortDescription", StringType, nullable = false)
    ,StructField("Description", StringType, nullable = false)
    ,StructField("Business", StringType, nullable = false)
    ,StructField("Technos", StringType, nullable = false)
    ,StructField("Status", StringType, nullable = false)
    ,StructField("LeadCode", StringType, nullable = false)
  ))

  val SalesPeriod: StructType = StructType (List(
    StructField("Id", StringType, nullable = false)
    ,StructField("IdFiscal", StringType, nullable = false)
    ,StructField("StartDate", TimestampType, nullable = false)
    ,StructField("EndDate", TimestampType, nullable = false)
    ,StructField("Label", StringType, nullable = false)
    ,StructField("VatRate", IntegerType, nullable = false)
    ,StructField("GenerateCommercialIncentives", BooleanType, nullable = false)
  ))

  val SalesPhasis: StructType = StructType (List(
    StructField("Id", StringType, nullable = false)
    ,StructField("IdProject", StringType, nullable = false)
    ,StructField("IdFiscal", StringType, nullable = false)
    ,StructField("IdKind", StringType, nullable = false)
    ,StructField("Name", StringType, nullable = false)
    ,StructField("DocumentLibrary", StringType, nullable = false)
    ,StructField("GlobalCost", DoubleType, nullable = false)
    ,StructField("GlobalPrice", DoubleType, nullable = false)
    ,StructField("GlobalMargin", DoubleType, nullable = false)
    ,StructField("StartDate", TimestampType, nullable = true)
    ,StructField("EndDate", TimestampType, nullable = true)
    ,StructField("Description", StringType, nullable = false)
    ,StructField("ClientReference", StringType, nullable = false)
    ,StructField("SprintDuration", IntegerType, nullable = true)
  ))

  val SalesProject: StructType = StructType (List(
    StructField("Id", StringType, nullable = false)
    ,StructField("IdFiscal", StringType, nullable = false)
    ,StructField("IdCustomer", StringType, nullable = false)
    ,StructField("Name", StringType, nullable = false)
    ,StructField("Actif", BooleanType, nullable = true)
  ))

  val SalesProjectKind: StructType = StructType (List(
    StructField("Id", StringType, nullable = false)
    ,StructField("Code", StringType, nullable = false)
    ,StructField("Name", StringType, nullable = false)
  ))

  val SalesUser: StructType = StructType (List(
    StructField("Id", StringType, nullable = false)
    ,StructField("IdSupplier", StringType, nullable = false)
    ,StructField("IdManager", StringType, nullable = false)
    ,StructField("FirstName", StringType, nullable = false)
    ,StructField("LastName", StringType, nullable = false)
    ,StructField("EMail", StringType, nullable = false)
    ,StructField("Login", StringType, nullable = false)
    ,StructField("StartDate", TimestampType, nullable = false)
    ,StructField("EndDate", TimestampType, nullable = true)
    ,StructField("VacationDuePrevious", DoubleType, nullable = true)
    ,StructField("VacationTakenPrevious", DoubleType, nullable = true)
    ,StructField("VacationDue", DoubleType, nullable = true)
    ,StructField("VacationTaken", DoubleType, nullable = true)
    ,StructField("RttDue", DoubleType, nullable = true)
    ,StructField("RttTaken", DoubleType, nullable = true)
    ,StructField("Address1", StringType, nullable = true)
    ,StructField("Address2", StringType, nullable = true)
    ,StructField("Address3", StringType, nullable = true)
    ,StructField("ZipCode", StringType, nullable = true)
    ,StructField("Town", StringType, nullable = true)
    ,StructField("Birthday", TimestampType, nullable = true)
    ,StructField("Mobile", StringType, nullable = true)
    ,StructField("Photo", BinaryType, nullable = true)
    ,StructField("Iban", StringType, nullable = true)
    ,StructField("Bic", StringType, nullable = true)
    ,StructField("Gender", IntegerType, nullable = false)
    ,StructField("PayLabel", StringType, nullable = true)
    ,StructField("SocialNumber", StringType, nullable = true)
    ,StructField("JobTitle", StringType, nullable = false)
    ,StructField("ContractType", StringType, nullable = false)
    ,StructField("IsCadre", BooleanType, nullable = false)
    ,StructField("TimePercentage", IntegerType, nullable = true)
    ,StructField("MonthSalaryCount", IntegerType, nullable = false)
    ,StructField("Nationality", StringType, nullable = true)
    ,StructField("BirthTown", StringType, nullable = true)
    ,StructField("EmailPrivate", StringType, nullable = true)
    ,StructField("IsBanned", BooleanType, nullable = false)
    ,StructField("BanDateTime", TimestampType, nullable = true)
    ,StructField("UserCode", StringType, nullable = true)
    ,StructField("MaritalName", StringType, nullable = true)
    ,StructField("Section", StringType, nullable = true)
    ,StructField("ExpirationDate", TimestampType, nullable = true)
    ,StructField("ResidencePermitType", StringType, nullable = true)
    ,StructField("ResidencePermitNumber", StringType, nullable = true)
    ,StructField("ResidencePermitEndDate", StringType, nullable = true)
    ,StructField("ContractEndDate", TimestampType, nullable = true)
  ))

  val TimesheetInput: StructType = StructType (List(
    StructField("Id", StringType, nullable = false)
    ,StructField("IdValidator", StringType, nullable = true)
    ,StructField("IdPeriod", StringType, nullable = false)
    ,StructField("IdUser", StringType, nullable = false)
    ,StructField("Date", StringType, nullable = false)
    ,StructField("LastStatusDate", StringType, nullable = false)
    ,StructField("Status", StringType, nullable = false)
    ,StructField("ValidationComment", StringType, nullable = true)
  ))

  val TimesheetInputRow: StructType = StructType (List(
    StructField("Id", StringType, nullable = false)
    ,StructField("IdInput", StringType, nullable = false)
    ,StructField("IdIntervention", StringType, nullable = false)
    ,StructField("Date", TimestampType, nullable = false)
    ,StructField("PM", IntegerType, nullable = false)
    ,StructField("AM", IntegerType, nullable = false)
    ,StructField("Duration", IntegerType, nullable = false)
  ))

}
